name= input('Enter your name:')
print("Enter your name")
print(name)
age= input("Enter your age")
print("Enter your age")
print(age)
dream= input("Enter your dream")
print("Enter your dream")
print(dream)
print("Name:",name)
print("Age:",age)
print("Dream:",dream)
