Num_1 = int(input("Enter the first number:"))
Num_2 = int(input("Enter the second number:"))
print(Num_1>Num_2)
print(Num_1<Num_2)
print(Num_1==Num_2)
print(Num_1!=Num_2)
print(Num_1>=Num_2)
print(Num_1<=Num_2)